### ISSUE TITLE
User console 

### ISSUE THREAD

**Issue by matteo-s** [scc-digitalhub/AAC#138]
Design and implement a new user console, based on React.
Console should expose

* account management
* attributes management with editable
* profile viewer
* app connections
* authorized devices (with refresh tokens)
* sessions
* (2FA/MFA)
* audit

Subtasks
* [ ] new userConsoleController
* [ ] update myUserManager to handle profiles
* [ ] update myUserManager to handle authorized devices (depends on #140) 
* [ ] update myUserManager to handle sessions
* [ ] update myUserManager to handle audit
